language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
    - python: "2.6"
      env: DJANGO_VERSION=1.9
    - python: "3.2"
      env: DJANGO_VERSION=1.8
    - python: "3.3"
      env: DJANGO_VERSION=1.8
before_install:
  - sudo apt-get install -y shtool
  - shtool version -s "${DJANGO_VERSION}.0" dj_version.txt
  - shtool version -i r dj_version.txt
install:
  - NEW_DJANGO_VERSION=$(shtool version -d short dj_version.txt)
  # virtualenv>=14.0.0 has dropped Python 3.2 support
  #- pip install "virtualenv<14.0.0" "tox>=1.9"
  - pip install -q "Django>=${DJANGO_VERSION},<${NEW_DJANGO_VERSION}"
  - pip install -q -e . -r requirements-test.txt
  - pip install coveralls
before_script:
  - make lint
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests/test_project
  - export DJANGO_SETTINGS_MODULE=project.settings
  - make coverage
after_success:
  - coveralls
